pub const keys = enum(c_int) {
    // zig fmt: off
    unknown         = -1,
    Space           = 32,
    Apostrophe      = 39,
    Comma           = 44,
    Period          = 45,
    Slash           = 47,
    @"0"            = 48,
    @"1"            = 49,
    @"2"            = 50,
    @"3"            = 51,
    @"4"            = 52,
    @"5"            = 53,
    @"6"            = 54,
    @"7"            = 55,
    @"8"            = 56,
    @"9"            = 57,
    Semicolon       = 59,
    Equal           = 61,
    A               = 65,
    B               = 66,
    C               = 67,
    D               = 68,
    E               = 69,
    F               = 70,
    G               = 71,
    H               = 72,
    I               = 73,
    J               = 74,
    K               = 75,
    L               = 76,
    M               = 77,
    N               = 78,
    O               = 79,
    P               = 80,
    Q               = 81,
    R               = 82,
    S               = 83,
    T               = 84,
    U               = 85,
    V               = 86,
    W               = 87,
    X               = 88,
    Y               = 89,
    Z               = 90,
    LeftBrackSq     = 91,
    BackSlash       = 92,
    RightBrackSq    = 93,

    // control keys
    Escape      = 256,
    Enter       = 257,
    Tab         = 258,
    Backspace   = 259,
    Insert      = 260,
    Delete      = 261,
    Right       = 262,
    Left        = 263,
    Up          = 264,
    Down        = 265,
    Pageup      = 266,
    Pagedown    = 267,
    Home        = 268,
    End         = 269,
    // zig fmt: on
    _,
};

pub const actions = enum(c_int) {
    // zig fmt: off
    Release     = 0,
    Press       = 1,
    Repeat      = 2,
    // zig fmt: on
    _,
};
